-- MySQL Script generated by MySQL Workbench
-- Tue Aug 18 09:33:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campeonato` (
  `id_campeonato` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `participantes` VARCHAR(45) NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `id_campeonato_UNIQUE` (`id_campeonato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `id_equipe` INT NOT NULL,
  `nome_equipe` VARCHAR(45) NOT NULL,
  `jogadores` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_equipe`),
  UNIQUE INDEX `nome_equipe_UNIQUE` (`nome_equipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`campeonato_has_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`campeonato_has_equipe` (
  `campeonato_id_campeonato` INT NOT NULL,
  `equipe_id_equipe` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` DATE NOT NULL,
  PRIMARY KEY (`campeonato_id_campeonato`),
  INDEX `fk_campeonato_has_equipe_equipe1_idx` (`equipe_id_equipe` ASC) VISIBLE,
  INDEX `fk_campeonato_has_equipe_campeonato_idx` (`campeonato_id_campeonato` ASC) VISIBLE,
  UNIQUE INDEX `equipe_id_equipe_UNIQUE` (`equipe_id_equipe` ASC) VISIBLE,
  CONSTRAINT `fk_campeonato_has_equipe_campeonato`
    FOREIGN KEY (`campeonato_id_campeonato`)
    REFERENCES `mydb`.`campeonato` (`id_campeonato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campeonato_has_equipe_equipe1`
    FOREIGN KEY (`equipe_id_equipe`)
    REFERENCES `mydb`.`equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` CHAR(11) NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `data_nacimento_cliente` DATE NOT NULL,
  `endereco` VARCHAR(225) NOT NULL,
  `CEP_cliente` DATETIME(13) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculos` (
  `id_veiculos` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `data_fabricacao` DATE NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NULL,
  `cliente_cpf_cliente` INT NOT NULL,
  PRIMARY KEY (`cliente_cpf_cliente`),
  INDEX `fk_veiculos_cliente1_idx` (`cliente_cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `id_veiculos_UNIQUE` (`id_veiculos` ASC) VISIBLE,
  CONSTRAINT `fk_table1_cliente1`
    FOREIGN KEY (`id_veiculos`)
    REFERENCES `mydb`.`cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_cliente1`
    FOREIGN KEY (`cliente_cpf_cliente`)
    REFERENCES `mydb`.`cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serviços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serviços` (
  `CNPJ` CHAR(14) NOT NULL,
  `modelos_veiculos` VARCHAR(45) NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  `nome_oficina` VARCHAR(45) NOT NULL,
  `veiculos_id_veiculos` INT NOT NULL,
  `veiculos_cliente_cpf_cliente` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_serviços_veiculos1_idx` (`veiculos_id_veiculos` ASC, `veiculos_cliente_cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `veiculos_id_veiculos_UNIQUE` (`veiculos_id_veiculos` ASC) VISIBLE,
  CONSTRAINT `fk_serviços_veiculos1`
    FOREIGN KEY (`veiculos_id_veiculos` , `veiculos_cliente_cpf_cliente`)
    REFERENCES `mydb`.`veiculos` (`id_veiculos` , `cliente_cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` CHAR(11) NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `data_nacimento_cliente` DATE NOT NULL,
  `endereco` VARCHAR(225) NOT NULL,
  `CEP_cliente` DATETIME(13) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prato` (
  `id_pedido` INT NOT NULL,
  `nome_prato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `numero_pedido` INT NOT NULL,
  `cliente_cpf` CHAR(11) NOT NULL,
  `prato_id_pedido` INT NOT NULL,
  INDEX `fk_pedido_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  INDEX `fk_pedido_prato1_idx` (`prato_id_pedido` ASC) VISIBLE,
  PRIMARY KEY (`prato_id_pedido`),
  UNIQUE INDEX `numero_pedido_UNIQUE` (`numero_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_prato1`
    FOREIGN KEY (`prato_id_pedido`)
    REFERENCES `mydb`.`prato` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_pedido` (
  `prato_id_pedido` INT NOT NULL,
  `quantidade_prato` INT NOT NULL,
  `pedido_numero_pedido` INT NOT NULL,
  `pedido_cliente_cpf` CHAR(11) NOT NULL,
  `pedido_prato_id_pedido` INT NOT NULL,
  INDEX `fk_pedido_has_prato_prato1_idx` (`prato_id_pedido` ASC) VISIBLE,
  PRIMARY KEY (`prato_id_pedido`),
  UNIQUE INDEX `pedido_numero_pedido_UNIQUE` (`pedido_numero_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_prato_prato1`
    FOREIGN KEY (`prato_id_pedido`)
    REFERENCES `mydb`.`prato` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_pedido_pedido1`
    FOREIGN KEY (`pedido_numero_pedido` , `pedido_cliente_cpf` , `pedido_prato_id_pedido`)
    REFERENCES `mydb`.`pedido` (`numero_pedido` , `cliente_cpf` , `prato_id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` CHAR(11) NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `data_nacimento_cliente` DATE NOT NULL,
  `endereco` VARCHAR(225) NOT NULL,
  `CEP_cliente` DATETIME(13) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `nome_pet` VARCHAR(45) NOT NULL,
  `data_nacimento_pet` DATE NOT NULL,
  `id_pet` INT NOT NULL,
  `cliente_cpf_cliente` INT NOT NULL,
  PRIMARY KEY (`cliente_cpf_cliente`),
  INDEX `fk_pets_cliente2_idx` (`cliente_cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `id_pet_UNIQUE` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_pets_cliente2`
    FOREIGN KEY (`cliente_cpf_cliente`)
    REFERENCES `mydb`.`cliente` (`cpf_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atendimeto` (
  `CNPJ` CHAR(14) NOT NULL,
  `nome_atendimento` VARCHAR(45) NOT NULL,
  `pets_id_pet` INT NOT NULL,
  `pets_cliente_cpf` INT NOT NULL,
  `pets_cliente_cpf1` INT NOT NULL,
  `data_atendimento` DATE NOT NULL,
  `hdescricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_atendimeto_pets1_idx` (`pets_id_pet` ASC, `pets_cliente_cpf` ASC, `pets_cliente_cpf1` ASC) VISIBLE,
  CONSTRAINT `fk_atendimeto_pets1`
    FOREIGN KEY (`pets_id_pet`)
    REFERENCES `mydb`.`pets` (`id_pet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuário` (
  `idusuario` INT NOT NULL,
  `CPF_usuario` CHAR(11) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF_usuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filme` (
  `id_usuario` INT NOT NULL,
  `nome_filme` VARCHAR(45) NOT NULL,
  `diretor_filme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visualização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visualização` (
  `usuário_cpf` CHAR(11) NOT NULL,
  `filme_usuário_idusuario` INT NOT NULL,
  `data_assistida` DATETIME(13) NOT NULL,
  `avaliacao_usuario` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`usuário_cpf`),
  INDEX `fk_usuário_has_filme_filme1_idx` (`filme_usuário_idusuario` ASC) VISIBLE,
  INDEX `fk_usuário_has_filme_usuário1_idx` (`usuário_cpf` ASC) VISIBLE,
  UNIQUE INDEX `filme_usuário_idusuario_UNIQUE` (`filme_usuário_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuário_has_filme_usuário1`
    FOREIGN KEY (`usuário_cpf`)
    REFERENCES `mydb`.`usuário` (`CPF_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuário_has_filme_filme1`
    FOREIGN KEY (`filme_usuário_idusuario`)
    REFERENCES `mydb`.`filme` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `CPF_professor` CHAR(11) NOT NULL,
  `nome_professor` VARCHAR(45) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`CPF_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `cnpj` CHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_criacao` DATE NOT NULL,
  `professores` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor_curso` (
  `professor_cpf` CHAR(11) NOT NULL,
  `carga _horaria` DATETIME(10) NOT NULL,
  `curso_cnpj` CHAR(14) NOT NULL,
  PRIMARY KEY (`professor_cpf`),
  INDEX `fk_professor_has_curso_professor1_idx` (`professor_cpf` ASC) VISIBLE,
  INDEX `fk_professor_curso_curso1_idx` (`curso_cnpj` ASC) VISIBLE,
  UNIQUE INDEX `curso_cnpj_UNIQUE` (`curso_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_professor_has_curso_professor1`
    FOREIGN KEY (`professor_cpf`)
    REFERENCES `mydb`.`professor` (`CPF_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_curso_curso1`
    FOREIGN KEY (`curso_cnpj`)
    REFERENCES `mydb`.`curso` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hóspede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hóspede` (
  `cpf` CHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `quarto` VARCHAR(45) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `quarto_UNIQUE` (`quarto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quarto` (
  `numero_quarto` INT NOT NULL,
  PRIMARY KEY (`numero_quarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `idreserva` INT NOT NULL,
  `hóspede_nome` VARCHAR(45) NOT NULL,
  `quarto_numero_quarto` INT NOT NULL,
  INDEX `fk_reserva_hóspede1_idx` (`hóspede_nome` ASC) VISIBLE,
  INDEX `fk_reserva_quarto1_idx` (`quarto_numero_quarto` ASC) VISIBLE,
  PRIMARY KEY (`idreserva`),
  UNIQUE INDEX `quarto_numero_quarto_UNIQUE` (`quarto_numero_quarto` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_hóspede1`
    FOREIGN KEY (`hóspede_nome`)
    REFERENCES `mydb`.`hóspede` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_quarto1`
    FOREIGN KEY (`quarto_numero_quarto`)
    REFERENCES `mydb`.`quarto` (`numero_quarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `cpf` CHAR(11) NOT NULL,
  `nome_medico` VARCHAR(45) NOT NULL,
  `data_nacimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `cpf_paciente` CHAR(11) NOT NULL,
  `nome_paciente` VARCHAR(45) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`cpf_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`internação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`internação` (
  `medico_cpf` CHAR(11) NOT NULL,
  `paciente_cpf_paciente` CHAR(11) NOT NULL,
  `paciente_medico_cpf` CHAR(11) NOT NULL,
  `data_internacao` DATETIME(13) NOT NULL,
  INDEX `fk_internação_paciente1_idx` (`paciente_cpf_paciente` ASC, `paciente_medico_cpf` ASC) VISIBLE,
  PRIMARY KEY (`paciente_cpf_paciente`),
  UNIQUE INDEX `medico_cpf_UNIQUE` (`medico_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_internação_medico1`
    FOREIGN KEY (`medico_cpf`)
    REFERENCES `mydb`.`medico` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internação_paciente1`
    FOREIGN KEY (`paciente_cpf_paciente` , `paciente_medico_cpf`)
    REFERENCES `mydb`.`paciente` (`cpf_paciente` , `data_nacimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante` (
  `cpf` CHAR(11) NOT NULL,
  `nome_participante` VARCHAR(45) NOT NULL,
  `data_nacimento` DATE NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `idevento` INT NOT NULL,
  `nome_evento` VARCHAR(255) NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `idevento_UNIQUE` (`idevento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante_has_evento` (
  `participante_cpf` CHAR(11) NOT NULL,
  `evento_idevento` INT NOT NULL,
  PRIMARY KEY (`participante_cpf`),
  INDEX `fk_participante_has_evento_evento1_idx` (`evento_idevento` ASC) VISIBLE,
  INDEX `fk_participante_has_evento_participante1_idx` (`participante_cpf` ASC) VISIBLE,
  UNIQUE INDEX `evento_idevento_UNIQUE` (`evento_idevento` ASC) VISIBLE,
  CONSTRAINT `fk_participante_has_evento_participante1`
    FOREIGN KEY (`participante_cpf`)
    REFERENCES `mydb`.`participante` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_has_evento_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `mydb`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palestrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palestrante` (
  `cpf_palestrante` CHAR(11) NOT NULL,
  `nome_paletrante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf_palestrante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palestrante_has_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palestrante_has_evento` (
  `cpf_palestrante` CHAR(11) NOT NULL,
  `evento_idevento` INT NOT NULL,
  PRIMARY KEY (`cpf_palestrante`),
  INDEX `fk_palestrante_has_evento_evento1_idx` (`evento_idevento` ASC) VISIBLE,
  INDEX `fk_palestrante_has_evento_palestrante1_idx` (`cpf_palestrante` ASC) VISIBLE,
  UNIQUE INDEX `evento_idevento_UNIQUE` (`evento_idevento` ASC) VISIBLE,
  CONSTRAINT `fk_palestrante_has_evento_palestrante1`
    FOREIGN KEY (`cpf_palestrante`)
    REFERENCES `mydb`.`palestrante` (`cpf_palestrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palestrante_has_evento_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `mydb`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` CHAR(11) NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `data_nacimento_cliente` DATE NOT NULL,
  `endereco` VARCHAR(225) NOT NULL,
  `CEP_cliente` DATETIME(13) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `endereco_UNIQUE` (`endereco` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereços` (
  `id_endereços` INT NULL,
  `local` VARCHAR(45) NOT NULL,
  `nome_rua` VARCHAR(45) NOT NULL,
  `cliente_cpf` INT NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  INDEX `fk_endereços_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  UNIQUE INDEX `cliente_cpf_UNIQUE` (`cliente_cpf` ASC) VISIBLE,
  PRIMARY KEY (`CEP`),
  CONSTRAINT `fk_endereços_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `id_pedidos` INT NOT NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_pedidos_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  UNIQUE INDEX `cliente_cpf_UNIQUE` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `tipo_categoria` INT NOT NULL,
  `nome_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `nome_produto` VARCHAR(225) NOT NULL,
  `id_produto` INT NOT NULL,
  `categoria_tipo_categoria` INT NOT NULL,
  INDEX `fk_produtos_categoria1_idx` (`categoria_tipo_categoria` ASC) VISIBLE,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `categoria_tipo_categoria_UNIQUE` (`categoria_tipo_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categoria1`
    FOREIGN KEY (`categoria_tipo_categoria`)
    REFERENCES `mydb`.`categoria` (`tipo_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos_has_produtos` (
  `pedidos_id_pedidos` INT NOT NULL,
  `pedidos_cliente_cpf` INT NOT NULL,
  `produtos_id_produto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pedidos_id_pedidos`),
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`produtos_id_produto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`pedidos_id_pedidos` ASC, `pedidos_cliente_cpf` ASC) VISIBLE,
  UNIQUE INDEX `produtos_id_produto_UNIQUE` (`produtos_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedidos` , `pedidos_cliente_cpf`)
    REFERENCES `mydb`.`pedidos` (`id_pedidos` , `cliente_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id_produto`)
    REFERENCES `mydb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `CNPJ` CHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`CNPJ`),
  UNIQUE INDEX `id_fornecedor_UNIQUE` (`id_fornecedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `id_pedido` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  `pagamentoscol` VARCHAR(45) NULL,
  `pedidos_id_pedidos` INT NOT NULL,
  `pedidos_cliente_cpf` INT NOT NULL,
  `data_pagamento` DATETIME(13) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pagamentos_pedidos1_idx` (`pedidos_id_pedidos` ASC, `pedidos_cliente_cpf` ASC) VISIBLE,
  UNIQUE INDEX `pedidos_cliente_cpf_UNIQUE` (`pedidos_cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_pagamentos_pedidos1`
    FOREIGN KEY (`pedidos_id_pedidos` , `pedidos_cliente_cpf`)
    REFERENCES `mydb`.`pedidos` (`id_pedidos` , `cliente_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor_has_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor_has_produtos` (
  `fornecedor_CNPJ` CHAR(14) NOT NULL,
  `id_produto` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_fornecedor_has_produtos_produtos1_idx` (`id_produto` ASC) VISIBLE,
  INDEX `fk_fornecedor_has_produtos_fornecedor1_idx` (`fornecedor_CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `fornecedor_CNPJ_UNIQUE` (`fornecedor_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_has_produtos_fornecedor1`
    FOREIGN KEY (`fornecedor_CNPJ`)
    REFERENCES `mydb`.`fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fornecedor_has_produtos_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
